import type { CrossEnrollmentRequest } from "@/lib/types";

export const crossEnrollmentRequests: CrossEnrollmentRequest[] = [
  {
    id: "ce-1",
    studentId: "u-ol2",
    studentName: "Roshan Perera",
    type: "ol-to-cohort",
    targetModuleId: "m-cs201",
    reason: "I work as a junior developer and want formal database credit from the CS programme.",
    status: "pending",
    requestedAt: "2026-06-25T10:00:00Z",
    paymentStatus: "pending",
  },
  {
    id: "ce-2",
    studentId: "u-st3",
    studentName: "Dinuka Bandara",
    type: "cohort-to-cohort",
    targetModuleId: "m-cs202",
    reason: "I want to take Web Development as an elective alongside my core modules.",
    status: "pending",
    requestedAt: "2026-06-24T15:30:00Z",
    paymentStatus: "pending",
  },
  {
    id: "ce-3",
    studentId: "u-st1",
    studentName: "Kasun Rajapaksa",
    type: "cohort-to-ol",
    targetCourseId: "ol-1",
    reason: "Interested in the UX design short course.",
    status: "approved",
    requestedAt: "2026-05-10T09:00:00Z",
    registrarNotes: "Free course — auto approved.",
    paymentStatus: "confirmed",
  },
  {
    id: "ce-4",
    studentId: "u-ol1",
    studentName: "Ishara Madushani",
    type: "ol-to-cohort",
    targetModuleId: "m-cs101",
    reason: "I want formal credit for Introduction to Programming alongside my Open Learning courses.",
    status: "approved",
    requestedAt: "2026-05-02T09:00:00Z",
    registrarNotes: "Approved — payment confirmed. Student now has full cohort access to CS101.",
    paymentStatus: "confirmed",
  },
];
