import type { Module } from "@/lib/types";

export const modules: Module[] = [
  {
    id: "m-cs101",
    code: "CS101",
    name: "Introduction to Programming",
    programId: "p-cs",
    semesterId: "sem-cs-1",
    creditValue: 15,
    learningOutcomes:
      "Write structured programs in Python; apply control flow, functions and basic data structures.",
    prerequisiteModuleIds: [],
    assessmentBreakdown: { assignments: 30, quizzes: 20, finalExam: 50 },
    primaryLecturerId: "u-lec3",
    lecturerIds: ["u-lec3"],
    status: "active",
    isShared: false,
    isCrossStreamEnabled: false,
    sequentialLectures: true,
  },
  {
    id: "m-cs102",
    code: "CS102",
    name: "Mathematics for Computing",
    programId: "p-cs",
    semesterId: "sem-cs-1",
    creditValue: 15,
    learningOutcomes: "Apply discrete mathematics, logic and linear algebra to computing problems.",
    prerequisiteModuleIds: [],
    assessmentBreakdown: { assignments: 20, quizzes: 20, finalExam: 60 },
    primaryLecturerId: "u-lec3",
    lecturerIds: ["u-lec3"],
    status: "active",
    isShared: false,
    isCrossStreamEnabled: false,
  },
  {
    id: "m-cs201",
    code: "CS201",
    name: "Database Management Systems",
    programId: "p-cs",
    semesterId: "sem-cs-2",
    creditValue: 20,
    learningOutcomes:
      "Design relational schemas, write SQL queries, apply normalisation, and understand transaction management.",
    prerequisiteModuleIds: ["m-cs101"],
    assessmentBreakdown: { assignments: 25, quizzes: 15, finalExam: 60 },
    primaryLecturerId: "u-lec1",
    lecturerIds: ["u-lec1"],
    status: "active",
    isShared: false,
    isCrossStreamEnabled: true,
  },
  {
    id: "m-cs202",
    code: "CS202",
    name: "Web Application Development",
    programId: "p-cs",
    semesterId: "sem-cs-2",
    creditValue: 20,
    learningOutcomes:
      "Build full-stack web applications using modern frameworks, REST APIs and responsive design.",
    prerequisiteModuleIds: ["m-cs101"],
    assessmentBreakdown: { assignments: 40, quizzes: 10, finalExam: 50 },
    primaryLecturerId: "u-lec2",
    lecturerIds: ["u-lec2"],
    status: "active",
    isShared: true,
    isCrossStreamEnabled: true,
  },
  {
    id: "m-cs203",
    code: "CS203",
    name: "Data Structures & Algorithms",
    programId: "p-cs",
    semesterId: "sem-cs-2",
    creditValue: 20,
    learningOutcomes: "Analyse algorithm complexity; implement core data structures and sorting/searching.",
    prerequisiteModuleIds: ["m-cs101"],
    assessmentBreakdown: { assignments: 30, quizzes: 20, finalExam: 50 },
    primaryLecturerId: "u-lec1",
    lecturerIds: ["u-lec1"],
    status: "active",
    isShared: false,
    isCrossStreamEnabled: false,
  },
  {
    id: "m-it101",
    code: "IT101",
    name: "Networking Fundamentals",
    programId: "p-it",
    semesterId: "sem-it-1",
    creditValue: 15,
    learningOutcomes: "Understand OSI/TCP-IP models, subnetting and basic network configuration.",
    prerequisiteModuleIds: [],
    assessmentBreakdown: { assignments: 30, quizzes: 20, finalExam: 50 },
    primaryLecturerId: "u-lec2",
    lecturerIds: ["u-lec2"],
    status: "active",
    isShared: false,
    isCrossStreamEnabled: false,
  },
  {
    id: "m-bus101",
    code: "BUS101",
    name: "Principles of Management",
    programId: "p-bus",
    semesterId: "sem-bus-1",
    creditValue: 15,
    learningOutcomes: "Understand core management functions and organisational behaviour.",
    prerequisiteModuleIds: [],
    assessmentBreakdown: { assignments: 40, quizzes: 10, finalExam: 50 },
    primaryLecturerId: "",
    lecturerIds: [],
    status: "draft",
    isShared: false,
    isCrossStreamEnabled: false,
  },
  {
    id: "m-bus102",
    code: "BUS102",
    name: "Financial Accounting",
    programId: "p-bus",
    semesterId: "sem-bus-1",
    creditValue: 15,
    learningOutcomes: "Prepare and interpret basic financial statements.",
    prerequisiteModuleIds: [],
    assessmentBreakdown: { assignments: 30, quizzes: 20, finalExam: 50 },
    primaryLecturerId: "",
    lecturerIds: [],
    status: "draft",
    isShared: false,
    isCrossStreamEnabled: false,
  },
];
