import type { Program, Intake } from "@/lib/types";

export const programs: Program[] = [
  {
    id: "p-cs",
    name: "BSc (Hons) Computer Science",
    code: "BSCCS",
    description:
      "A four-year honours degree covering software engineering, databases, algorithms, AI and systems. Accredited and industry-aligned.",
    level: "degree",
    durationYears: 4,
    totalCredits: 480,
    department: "Computing",
    hodId: "u-hod",
    status: "active",
    entryRequirements: "3 A/L passes including Mathematics, or recognised foundation programme.",
    semesters: [
      {
        id: "sem-cs-1",
        programId: "p-cs",
        name: "Year 1 - Semester 1",
        year: 1,
        semesterNumber: 1,
        startDate: "2024-02-01",
        endDate: "2024-06-15",
        status: "completed",
        moduleIds: ["m-cs101", "m-cs102"],
      },
      {
        id: "sem-cs-2",
        programId: "p-cs",
        name: "Year 1 - Semester 2",
        year: 1,
        semesterNumber: 2,
        startDate: "2026-02-01",
        endDate: "2026-06-30",
        status: "active",
        moduleIds: ["m-cs201", "m-cs202", "m-cs203"],
      },
    ],
  },
  {
    id: "p-it",
    name: "Higher National Diploma in Information Technology",
    code: "HNDIT",
    description:
      "A two-year practical diploma producing job-ready IT professionals with strong programming and networking foundations.",
    level: "hnd",
    durationYears: 2,
    totalCredits: 240,
    department: "Computing",
    hodId: "u-hod",
    status: "active",
    entryRequirements: "O/L with 6 passes including Mathematics and English.",
    semesters: [
      {
        id: "sem-it-1",
        programId: "p-it",
        name: "Year 1 - Semester 1",
        year: 1,
        semesterNumber: 1,
        startDate: "2026-02-01",
        endDate: "2026-06-30",
        status: "active",
        moduleIds: ["m-it101"],
      },
    ],
  },
  {
    id: "p-bus",
    name: "Diploma in Business Management",
    code: "DBM",
    description:
      "A one-year diploma covering management principles, accounting, marketing and entrepreneurship.",
    level: "diploma",
    durationYears: 1,
    totalCredits: 120,
    department: "Business",
    hodId: "u-hod2",
    status: "submitted",
    entryRequirements: "O/L with 6 passes.",
    hodComments:
      "Submitted for Program Admin review. All four core modules and assessment breakdowns are defined.",
    semesters: [
      {
        id: "sem-bus-1",
        programId: "p-bus",
        name: "Year 1 - Semester 1",
        year: 1,
        semesterNumber: 1,
        startDate: "2026-09-01",
        endDate: "2027-01-31",
        status: "upcoming",
        moduleIds: ["m-bus101", "m-bus102"],
      },
    ],
  },
];

export const intakes: Intake[] = [
  {
    id: "in-cs-2024",
    programId: "p-cs",
    label: "2024 Intake",
    applicationOpenDate: "2023-10-01",
    applicationCloseDate: "2023-12-31",
    maxCapacity: 120,
    academicStartDate: "2024-02-01",
    status: "closed",
    enrolledStudentIds: ["u-st1", "u-st2", "u-st3", "u-st4", "u-st5"],
  },
  {
    id: "in-cs-2026",
    programId: "p-cs",
    label: "2026 Intake",
    applicationOpenDate: "2025-10-01",
    applicationCloseDate: "2026-08-31",
    maxCapacity: 150,
    academicStartDate: "2026-09-01",
    status: "open",
    enrolledStudentIds: [],
  },
  {
    id: "in-it-2026",
    programId: "p-it",
    label: "2026 Intake",
    applicationOpenDate: "2025-10-01",
    applicationCloseDate: "2026-08-31",
    maxCapacity: 80,
    academicStartDate: "2026-09-01",
    status: "open",
    enrolledStudentIds: [],
  },
];
