import type { Quiz, QuizSubmission } from "@/lib/types";

export const quizzes: Quiz[] = [
  {
    id: "qz-201-1",
    moduleId: "m-cs201",
    lectureId: "lec-201-2",
    title: "Quiz 1 — Relational Model",
    instructions: "Answer all questions. You have one attempt.",
    totalMarks: 10,
    timeLimitMinutes: 20,
    availableFrom: "2026-02-12T09:00",
    availableTo: "2026-07-30T23:59",
    allowedAttempts: 1,
    randomiseOrder: false,
    showAnswersAfter: true,
    status: "active",
    createdByLecturerId: "u-lec1",
    verifiedAt: "2026-02-11T10:00:00Z",
    questions: [
      {
        id: "q1",
        type: "mcq-single",
        text: "Which key uniquely identifies a row in a relation?",
        options: ["Foreign key", "Primary key", "Candidate index", "Composite alias"],
        correctAnswer: "Primary key",
        marks: 2,
        explanation: "A primary key uniquely identifies each tuple.",
      },
      {
        id: "q2",
        type: "true-false",
        text: "A foreign key can reference the primary key of another table.",
        correctAnswer: "True",
        marks: 2,
      },
      {
        id: "q3",
        type: "mcq-multi",
        text: "Which of the following are integrity constraints? (Select all)",
        options: ["Entity integrity", "Referential integrity", "Temporal locking", "Domain constraint"],
        correctAnswer: ["Entity integrity", "Referential integrity", "Domain constraint"],
        marks: 3,
      },
      {
        id: "q4",
        type: "short-answer",
        text: "In one sentence, define a candidate key.",
        correctAnswer: "A minimal set of attributes that can uniquely identify a tuple.",
        marks: 3,
        explanation: "Graded manually by the lecturer.",
      },
    ],
  },
  {
    id: "qz-201-2",
    moduleId: "m-cs201",
    lectureId: "lec-201-3",
    title: "Quiz 2 — SQL Basics",
    instructions: "20 minute quiz covering SELECT statements.",
    totalMarks: 8,
    timeLimitMinutes: 20,
    availableFrom: "2026-02-20T09:00",
    availableTo: "2026-07-30T23:59",
    allowedAttempts: 2,
    randomiseOrder: true,
    showAnswersAfter: false,
    status: "active",
    createdByLecturerId: "u-lec1",
    submittedAt: "2026-02-18T15:00:00Z",
    questions: [
      {
        id: "q5",
        type: "mcq-single",
        text: "Which clause filters rows before grouping?",
        options: ["HAVING", "WHERE", "ORDER BY", "GROUP BY"],
        correctAnswer: "WHERE",
        marks: 2,
      },
      {
        id: "q6",
        type: "fill-blank",
        text: "The ______ function returns the number of rows.",
        correctAnswer: "COUNT",
        marks: 2,
      },
      {
        id: "q7",
        type: "mcq-single",
        text: "Which keyword removes duplicate rows from a result?",
        options: ["UNIQUE", "DISTINCT", "ONLY", "SET"],
        correctAnswer: "DISTINCT",
        marks: 2,
      },
      {
        id: "q8",
        type: "true-false",
        text: "ORDER BY sorts ascending by default.",
        correctAnswer: "True",
        marks: 2,
      },
    ],
  },
  {
    id: "qz-202-1",
    moduleId: "m-cs202",
    title: "Quiz 1 — HTML & CSS",
    instructions: "Quick check on web fundamentals.",
    totalMarks: 6,
    timeLimitMinutes: 15,
    availableFrom: "2026-02-15T09:00",
    availableTo: "2026-07-30T23:59",
    allowedAttempts: 1,
    randomiseOrder: false,
    showAnswersAfter: true,
    status: "active",
    createdByLecturerId: "u-lec2",
    submittedAt: "2026-02-13T12:00:00Z",
    questions: [
      {
        id: "q9",
        type: "mcq-single",
        text: "Which tag defines the largest heading?",
        options: ["<h6>", "<head>", "<h1>", "<title>"],
        correctAnswer: "<h1>",
        marks: 3,
      },
      {
        id: "q10",
        type: "true-false",
        text: "Flexbox is a one-dimensional layout model.",
        correctAnswer: "True",
        marks: 3,
      },
    ],
  },
  {
    id: "ol-qz-1",
    moduleId: "ol-1",
    title: "Prototyping Knowledge Check",
    instructions: "A short check on interactive prototyping concepts.",
    totalMarks: 6,
    timeLimitMinutes: 10,
    availableFrom: "2026-06-01T09:00",
    availableTo: "2026-12-31T23:59",
    allowedAttempts: 2,
    randomiseOrder: false,
    showAnswersAfter: true,
    status: "active",
    createdByLecturerId: "u-lec2",
    verifiedAt: "2026-05-30T10:00:00Z",
    questions: [
      {
        id: "olq1",
        type: "mcq-single",
        text: "What is the main purpose of an interactive prototype?",
        options: ["Final production code", "Testing user flows before build", "Server configuration", "Database design"],
        correctAnswer: "Testing user flows before build",
        marks: 3,
        explanation: "Prototypes validate flows cheaply before development.",
      },
      {
        id: "olq2",
        type: "true-false",
        text: "Low-fidelity wireframes should include final colours and fonts.",
        correctAnswer: "False",
        marks: 3,
      },
    ],
  },
];

export const quizSubmissions: QuizSubmission[] = [
  {
    id: "qs-1",
    quizId: "qz-201-1",
    studentId: "u-st2",
    attemptedAt: "2026-02-13T10:00:00Z",
    answers: {
      q1: "Primary key",
      q2: "True",
      q3: ["Entity integrity", "Referential integrity", "Domain constraint"],
      q4: "A minimal unique identifier for a row.",
    },
    autoScore: 7,
    manualMarks: {},
    finalScore: 7,
    manualReviewPending: true,
  },
  {
    id: "qs-2",
    quizId: "qz-201-1",
    studentId: "u-st4",
    attemptedAt: "2026-02-14T14:00:00Z",
    answers: {
      q1: "Primary key",
      q2: "True",
      q3: ["Entity integrity", "Referential integrity"],
      q4: "Smallest set of columns identifying a tuple uniquely.",
    },
    autoScore: 4,
    manualMarks: {},
    finalScore: 4,
    manualReviewPending: true,
  },
];
