import type { User } from "@/lib/types";

export const users: User[] = [
  {
    id: "u-sa",
    name: "Amara Wickramasinghe",
    email: "superadmin@lms.ac.lk",
    role: "super-admin",
    status: "active",
    createdAt: "2023-01-10T08:00:00Z",
  },
  {
    id: "u-pa",
    name: "Nimal Fernando",
    email: "programadmin@lms.ac.lk",
    role: "program-admin",
    status: "active",
    createdAt: "2023-02-01T08:00:00Z",
    programIds: ["p-cs", "p-it", "p-bus"],
  },
  {
    id: "u-reg",
    name: "Sanduni Jayawardena",
    email: "registrar@lms.ac.lk",
    role: "registrar",
    status: "active",
    createdAt: "2023-02-05T08:00:00Z",
  },
  {
    id: "u-hod",
    name: "Dr. Ravindra Mendis",
    email: "hod.computing@lms.ac.lk",
    role: "hod",
    status: "active",
    createdAt: "2023-02-10T08:00:00Z",
    department: "Computing",
    programIds: ["p-cs", "p-it"],
  },
  {
    id: "u-hod2",
    name: "Dr. Kumari Bandara",
    email: "hod.business@lms.ac.lk",
    role: "hod",
    status: "active",
    createdAt: "2023-02-10T08:00:00Z",
    department: "Business",
    programIds: ["p-bus"],
  },
  {
    id: "u-lec1",
    name: "Dr. Priyanka Silva",
    email: "p.silva@lms.ac.lk",
    role: "lecturer",
    status: "active",
    createdAt: "2023-03-01T08:00:00Z",
    department: "Computing",
    specialisation: "Databases & Data Engineering",
    assignedModuleIds: ["m-cs201", "m-cs203"],
  },
  {
    id: "u-lec2",
    name: "Ms. Dilani Perera",
    email: "d.perera@lms.ac.lk",
    role: "lecturer",
    status: "active",
    createdAt: "2023-03-01T08:00:00Z",
    department: "Computing",
    specialisation: "Web & Mobile Development",
    assignedModuleIds: ["m-cs202"],
  },
  {
    id: "u-lec3",
    name: "Mr. Asela Gunawardena",
    email: "a.gunawardena@lms.ac.lk",
    role: "lecturer",
    status: "active",
    createdAt: "2023-03-05T08:00:00Z",
    department: "Computing",
    specialisation: "Algorithms",
    assignedModuleIds: ["m-cs101", "m-cs102"],
  },
  // Cohort students
  {
    id: "u-st1",
    name: "Kasun Rajapaksa",
    email: "kasun.r@student.lms.ac.lk",
    role: "cohort-student",
    status: "active",
    createdAt: "2024-01-15T08:00:00Z",
    studentId: "CS2024001",
    programId: "p-cs",
    intakeId: "in-cs-2024",
    currentSemesterId: "sem-cs-2",
    lastLogin: "2026-06-27T14:30:00Z",
    crossEnrolledModuleIds: [],
  },
  {
    id: "u-st2",
    name: "Tharushi Wijesinghe",
    email: "tharushi.w@student.lms.ac.lk",
    role: "cohort-student",
    status: "active",
    createdAt: "2024-01-15T08:00:00Z",
    studentId: "CS2024002",
    programId: "p-cs",
    intakeId: "in-cs-2024",
    currentSemesterId: "sem-cs-2",
    lastLogin: "2026-06-26T09:10:00Z",
  },
  {
    id: "u-st3",
    name: "Dinuka Bandara",
    email: "dinuka.b@student.lms.ac.lk",
    role: "cohort-student",
    status: "active",
    createdAt: "2024-01-15T08:00:00Z",
    studentId: "CS2024003",
    programId: "p-cs",
    intakeId: "in-cs-2024",
    currentSemesterId: "sem-cs-2",
    lastLogin: "2026-06-20T18:00:00Z",
  },
  {
    id: "u-st4",
    name: "Hashini Gunasekara",
    email: "hashini.g@student.lms.ac.lk",
    role: "cohort-student",
    status: "active",
    createdAt: "2024-01-15T08:00:00Z",
    studentId: "CS2024004",
    programId: "p-cs",
    intakeId: "in-cs-2024",
    currentSemesterId: "sem-cs-2",
    lastLogin: "2026-06-25T11:00:00Z",
  },
  {
    id: "u-st5",
    name: "Sahan Liyanage",
    email: "sahan.l@student.lms.ac.lk",
    role: "cohort-student",
    status: "active",
    createdAt: "2024-01-15T08:00:00Z",
    studentId: "CS2024005",
    programId: "p-cs",
    intakeId: "in-cs-2024",
    currentSemesterId: "sem-cs-2",
    lastLogin: "2026-06-15T08:00:00Z",
  },
  // OL students
  {
    id: "u-ol1",
    name: "Ishara Madushani",
    email: "ishara.m@gmail.com",
    role: "ol-student",
    status: "active",
    createdAt: "2025-09-01T08:00:00Z",
    crossEnrolledModuleIds: [],
  },
  {
    id: "u-ol2",
    name: "Roshan Perera",
    email: "roshan.p@gmail.com",
    role: "ol-student",
    status: "active",
    createdAt: "2025-10-12T08:00:00Z",
  },
  {
    id: "u-ol3",
    name: "Nethmi Senanayake",
    email: "nethmi.s@gmail.com",
    role: "ol-student",
    status: "active",
    createdAt: "2026-01-05T08:00:00Z",
  },
];

// Default demo user per role used by the role selector / switcher
export const demoUserByRole: Record<string, string> = {
  "super-admin": "u-sa",
  "program-admin": "u-pa",
  registrar: "u-reg",
  hod: "u-hod",
  lecturer: "u-lec1",
  "cohort-student": "u-st1",
  "ol-student": "u-ol1",
};

export const DEPARTMENTS = ["Computing", "Business", "Engineering", "Design", "Science"];
